services:
  # Base de datos PostgreSQL
  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: singletone
      POSTGRES_PASSWORD: singletonepass
      POSTGRES_DB: singletone
    ports:
      - "5432:5432"
    volumes:
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql

  # MongoDB para music
  mongo-music:
    image: mongo:6
    container_name: mongo-music
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./docker/mongo/music-init.js:/docker-entrypoint-initdb.d/init.js

  # MongoDB para library
  mongo-library:
    image: mongo:6
    container_name: mongo-library
    restart: always
    ports:
      - "27018:27017"
    volumes:
      - ./docker/mongo/library-init.js:/docker-entrypoint-initdb.d/init.js

  # Redis para cada microservicio
  redis-user:
    image: redis:7
    container_name: redis-user
    restart: always
    ports:
      - "6380:6379"
    volumes:
      - ./docker/redis/redis-user.conf:/usr/local/etc/redis/redis.conf

  redis-profile:
    image: redis:7
    container_name: redis-profile
    restart: always
    ports:
      - "6381:6379"
    volumes:
      - ./docker/redis/redis-profile.conf:/usr/local/etc/redis/redis.conf

  redis-music:
    image: redis:7
    container_name: redis-music
    restart: always
    ports:
      - "6382:6379"
    volumes:
      - ./docker/redis/redis-music.conf:/usr/local/etc/redis/redis.conf

  redis-library:
    image: redis:7
    container_name: redis-library
    restart: always
    ports:
      - "6383:6379"
    volumes:
      - ./docker/redis/redis-library.conf:/usr/local/etc/redis/redis.conf

  redis-recommendation:
    image: redis:7
    container_name: redis-recommendation
    restart: always
    ports:
      - "6384:6379"
    volumes:
      - ./docker/redis/redis-recommendation.conf:/usr/local/etc/redis/redis.conf

  redis-plan:
    image: redis:7
    container_name: redis-plan
    restart: always
    ports:
      - "6385:6379"
    volumes:
      - ./docker/redis/redis-plan.conf:/usr/local/etc/redis/redis.conf

  redis-gateway:
    image: redis:7
    container_name: redis-gateway
    restart: always
    ports:
      - "6386:6379"
    volumes:
      - ./docker/redis/redis-gateway.conf:/usr/local/etc/redis/redis.conf

  # Gateway NGINX
  nginx:
    image: nginx:latest
    container_name: apigateway
    ports:
      - "80:80"
    volumes:
      - ./apps/apigateway/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

  # Microservicio: User
  user-service:
    build:
      context: .
      dockerfile: apps/user-service/Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - redis-user
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=singletone
      - POSTGRES_PASSWORD=singletonepass
      - POSTGRES_DB=singletone
      - REDIS_HOST=redis-user
      - REDIS_PORT=6379

  # Microservicio: Profile
  profile-service:
    build:
      context: .
      dockerfile: apps/profile-service/Dockerfile
    ports:
      - "3001:3001"
    depends_on:
      - redis-profile
      - user-service
    environment:
      - PORT=3001
      - REDIS_HOST=redis-profile
      - REDIS_PORT=6379
      - USER_SERVICE_URL=http://user-service:3000

  # Microservicio: Plan
  plan-service:
    build:
      context: .
      dockerfile: apps/plan-service/Dockerfile
    ports:
      - "3004:3004"
    depends_on:
      - redis-plan
    environment:
      - PORT=3004
      - REDIS_HOST=redis-plan
      - REDIS_PORT=6379

  # Microservicio: Recommendation
  recommendation-service:
    build:
      context: .
      dockerfile: apps/recommendation-service/Dockerfile
    ports:
      - "3006:3006"
    depends_on:
      - redis-recommendation
    environment:
      - PORT=3006
      - REDIS_HOST=redis-recommendation
      - REDIS_PORT=6379

  # Microservicio: Music
  music-service:
    build:
      context: .
      dockerfile: apps/music-service/Dockerfile
    ports:
      - "3002:3002"
    depends_on:
      - mongo-music
      - redis-music
    environment:
      - PORT=3002
      - MONGO_HOST=mongo-music
      - MONGO_PORT=27017
      - MONGO_DB=music
      - REDIS_HOST=redis-music
      - REDIS_PORT=6379

  # Microservicio: Library
  library-service:
    build:
      context: .
      dockerfile: apps/library-service/Dockerfile
    ports:
      - "3003:3003"
    depends_on:
      - mongo-library
      - redis-library
    environment:
      - PORT=3003
      - MONGO_HOST=mongo-library
      - MONGO_PORT=27017
      - MONGO_DB=library
      - REDIS_HOST=redis-library
      - REDIS_PORT=6379